# Generated by Django 5.2.1 on 2025-06-04 00:02

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=150, verbose_name='Alias')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('nacionalidad', models.CharField(max_length=50, verbose_name='Nacionalidad')),
            ],
            options={
                'verbose_name': 'autor',
                'verbose_name_plural': 'autores',
                'db_table': 'autor',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción')),
                ('color', models.CharField(max_length=7, verbose_name='Color')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'etiqueta',
                'verbose_name_plural': 'etiquetas',
                'db_table': 'etiqueta',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Experiencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripcion')),
                ('fecha_creacion', models.DateField(default=datetime.datetime(2025, 6, 4, 0, 2, 53, 371424, tzinfo=datetime.timezone.utc), verbose_name='FechaCreacion')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='UsuarioId')),
            ],
            options={
                'verbose_name': 'experiencia',
                'verbose_name_plural': 'experiencias',
                'db_table': 'experiencias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=300)),
                ('fecha_publicacion', models.DateField(verbose_name='FechaPublicación')),
                ('autor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.autor', verbose_name='AutorId')),
            ],
            options={
                'verbose_name': 'libro',
                'verbose_name_plural': 'libros',
                'db_table': 'libros',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LibroEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime(2025, 6, 4, 0, 2, 53, 370415, tzinfo=datetime.timezone.utc), verbose_name='FechaCreacion')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('etiqueta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.etiqueta', verbose_name='EtiquetaId')),
                ('libro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.libros', verbose_name='LibroId')),
            ],
            options={
                'verbose_name': 'libro_etiqueta',
                'verbose_name_plural': 'libro_etiqueta',
                'db_table': 'libro_etiqueta',
                'ordering': ['id'],
            },
        ),
    ]
