# Generated by Django 5.2.1 on 2025-06-04 03:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='portada',
            field=models.ImageField(null=True, upload_to='', verbose_name='Portada'),
        ),
        migrations.AlterField(
            model_name='experiencias',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2025, 6, 4, 3, 23, 33, 563084, tzinfo=datetime.timezone.utc), verbose_name='FechaCreacion'),
        ),
        migrations.AlterField(
            model_name='libroetiqueta',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 4, 3, 23, 33, 563084, tzinfo=datetime.timezone.utc), verbose_name='FechaCreacion'),
        ),
    ]
