# Generated by Django 5.2.1 on 2025-06-04 04:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_experiencias_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencias',
            name='portada',
            field=models.ImageField(null=True, upload_to='fotosExperiencias', verbose_name='FotoExperiencias'),
        ),
        migrations.AlterField(
            model_name='experiencias',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2025, 6, 4, 4, 23, 49, 981640, tzinfo=datetime.timezone.utc), verbose_name='FechaCreacion'),
        ),
        migrations.AlterField(
            model_name='libroetiqueta',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 4, 4, 23, 49, 981640, tzinfo=datetime.timezone.utc), verbose_name='FechaCreacion'),
        ),
    ]
