# Generated by Django 5.2.1 on 2025-06-04 04:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_experiencias_portada_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiencias',
            old_name='portada',
            new_name='foto',
        ),
        migrations.AlterField(
            model_name='experiencias',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2025, 6, 4, 4, 29, 46, 780883, tzinfo=datetime.timezone.utc), verbose_name='FechaCreacion'),
        ),
        migrations.AlterField(
            model_name='libroetiqueta',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 4, 4, 29, 46, 779374, tzinfo=datetime.timezone.utc), verbose_name='FechaCreacion'),
        ),
    ]
