# Generated by Django 5.2.1 on 2025-10-26 01:02

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_portada_experiencias_foto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='etiqueta',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='core.etiqueta'),
        ),
        migrations.AlterField(
            model_name='experiencias',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2025, 10, 26, 1, 2, 32, 210351, tzinfo=datetime.timezone.utc), verbose_name='FechaCreacion'),
        ),
        migrations.AlterField(
            model_name='libroetiqueta',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 26, 1, 2, 32, 210351, tzinfo=datetime.timezone.utc), verbose_name='FechaCreacion'),
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=datetime.datetime(2025, 10, 26, 1, 2, 32, 210351, tzinfo=datetime.timezone.utc), verbose_name='FechaCreacion')),
                ('fecha_fin', models.DateField(default=datetime.datetime(2025, 10, 26, 1, 2, 32, 210351, tzinfo=datetime.timezone.utc), verbose_name='FechaCreacion')),
                ('observacion', models.CharField(max_length=300, verbose_name='Descripcion')),
                ('libro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.libros', verbose_name='LibroId')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='UsuarioId')),
            ],
            options={
                'verbose_name': 'prestamo',
                'verbose_name_plural': 'prestamos',
                'db_table': 'prestamo',
                'ordering': ['id'],
            },
        ),
    ]
