# Generated by Django 4.2.4 on 2025-12-12 23:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_etiqueta_padre_alter_experiencias_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='etiquetas',
            field=models.ManyToManyField(through='core.LibroEtiqueta', to='core.etiqueta'),
        ),
        migrations.AlterField(
            model_name='experiencias',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2025, 12, 12, 23, 15, 35, 780414, tzinfo=datetime.timezone.utc), verbose_name='FechaCreacion'),
        ),
        migrations.AlterField(
            model_name='libroetiqueta',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 12, 23, 15, 35, 780414, tzinfo=datetime.timezone.utc), verbose_name='FechaCreacion'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2025, 12, 12, 23, 15, 35, 781415, tzinfo=datetime.timezone.utc), verbose_name='FechaCreacion'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2025, 12, 12, 23, 15, 35, 781415, tzinfo=datetime.timezone.utc), verbose_name='FechaCreacion'),
        ),
    ]
