# Generated by Django 4.2.4 on 2025-12-12 23:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_libros_etiquetas_alter_experiencias_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libros',
            options={},
        ),
        migrations.RemoveField(
            model_name='libros',
            name='autor_id',
        ),
        migrations.AddField(
            model_name='libros',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.autor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experiencias',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2025, 12, 12, 23, 27, 48, 581201, tzinfo=datetime.timezone.utc), verbose_name='FechaCreacion'),
        ),
        migrations.AlterField(
            model_name='libroetiqueta',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 12, 23, 27, 48, 580202, tzinfo=datetime.timezone.utc), verbose_name='FechaCreacion'),
        ),
        migrations.AlterField(
            model_name='libros',
            name='fecha_publicacion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='libros',
            name='portada',
            field=models.ImageField(null=True, upload_to='portadasLibros'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2025, 12, 12, 23, 27, 48, 581201, tzinfo=datetime.timezone.utc), verbose_name='FechaCreacion'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2025, 12, 12, 23, 27, 48, 581201, tzinfo=datetime.timezone.utc), verbose_name='FechaCreacion'),
        ),
        migrations.AlterModelTable(
            name='libros',
            table=None,
        ),
    ]
